name: AntiEnchant
main: com.solmex.antienchant.AntiEnchant
version: ${project.version}
authors: [Solmex,Deaththinius]
permissions:
  ae.admin:
    description: AntiEnchant full permission.
    default: op
  ae.enchantbooks:
    description: Enchanting permission.
    default: op
  ae.unenchant:
    description: Unenchant permission.
    default: op
  ae.repair:
    description: Repair permission.
    default: op

